In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [2]:
# Load the trained Model
# Load scalarz pickle and onehot

model=load_model("model.h5")

# Load the encoder and scalar
with open("onehot_encoder_geo.pkl", "rb") as f:
    label_encoder_geo=pickle.load(f) 

with open("encoder_gender.pkl", "rb") as f:
    label_encoder_gender=pickle.load(f) 

with open("scaler.pkl", "rb") as f:
    scaler=pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [ ]:
# Example Data
input_data={
    "CreditScore":600,
    "Geography":"France",
    "Gender":"Male",
    "Age":23,
    "Tenure":1,
    "Balance":60000,
    "NumOfProducts":2,
    "HasCrCard":1,
    "IsActiveMember":1,
    "EstimatedSalary":50000,
}

In [25]:
encoder_geo=label_encoder_geo.transform([[input_data["Geography"]]])
encoded_geo=pd.DataFrame(encoder_geo.toarray(), columns=label_encoder_geo.get_feature_names_out(['Geography']))
encoded_geo

c:\Users\malle\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [26]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,23,1,60000,2,1,1,50000

In [27]:
# Encode Categorical Variables
input_df["Gender"]=label_encoder_gender.transform(input_df["Gender"])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,23,1,60000,2,1,1,50000

In [28]:
# Concatination one hot Encoded

input_df=pd.concat([input_df.drop("Geography", axis=1), encoded_geo], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,23,1,60000,2,1,1,50000,1.0,0.0,0.0

In [29]:
# Scaling the input 
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755, -1.51143782, -1.38944225, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [30]:
# Prediction Churn
Prediction=model.predict(input_scaled)
Prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step

array([[0.00537868]], dtype=float32)

In [32]:
Prediction_prop=Prediction[0][0]
Prediction_prop

np.float32(0.0053786766)

In [33]:
if Prediction_prop>0.5:
    print("The Customer is likely to churn")
else:
    print("The Customer is not likely to churn")

The Customer is not likely to churn